### PR TITLE
Create potato_sack.md

### PR DESCRIPTION
**Pull request by alonzi**
i want to start counting potatoes and figured we need a sack to put them in

### CODE REVIEW

**Comment by jx0109** [comment]
Like this?

**Comment by alonzi** [comment]
great job but i wanted two potatoes

**Comment by Kia0615** [comment]
All about potatoes

**Comment by smorty** [comment]
🥇

**Comment by Jo-Pan** [comment]
goooooood

**Comment by Rlmahoney** [comment]
comment

**Pull request merged**
